#!/usr/bin/env node
/**
 * sync-resume.mjs
 * Single source of truth pipeline: RESUME.md → resume-data.ts + PDF
 *
 * Usage: node scripts/sync-resume.mjs
 *    or: npm run sync
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { parseResume } from './parse-resume.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const TS_OUT = resolve(ROOT, 'src', 'app', 'data', 'resume-data.ts');

// ─── Parse ───────────────────────────────────────────────────────────────────

console.log('▸ Parsing RESUME.md…');
const R = parseResume();

// ─── Generate resume-data.ts ─────────────────────────────────────────────────

function q(s)    { return JSON.stringify(String(s ?? '')); }
function arr(a)  { return `[\n${a.map(s => `    ${q(s)},`).join('\n')}\n  ]`; }
function optArr(a) {
  if (!a || !a.length) return null;
  return `[\n${a.map(s => `      ${q(s)},`).join('\n')}\n    ]`;
}

const experienceTs = R.experience.map(exp => {
  const be = optArr(exp.backendBullets);
  return `    {
      company: ${q(exp.company)},
      location: ${q(exp.location)},
      role: ${q(exp.role)},
      period: ${q(exp.period)},
      bullets: ${arr(exp.bullets)},${be ? `\n      backendBullets: ${be},` : ''}
    }`;
}).join(',\n');

const projectsTs = R.projects.map(p => `    {
      name: ${q(p.name)},
      tech: ${q(p.stack.join(' · '))},
      period: ${q(p.period)},
      bullets: ${arr([p.body, ...p.bullets].filter(Boolean))},
    }`).join(',\n');

const educationTs = R.education.map(ed => `    {
      institution: ${q(ed.institution)},
      location: ${q(ed.location || '')},
      degree: ${q(ed.degree)},
      period: ${q(ed.period)},
    }`).join(',\n');

const coursesTs = R.courses.map(c => {
  const year = c.year ? `, year: ${q(c.year)}` : '';
  return `    { name: ${q(c.name)}, provider: ${q(c.provider)}${year} }`;
}).join(',\n');

const skillsTs = R.skills.map(s => `    ${q(s)},`).join('\n');

const ts = `// AUTO-GENERATED by scripts/sync-resume.mjs — edit RESUME.md, not this file.

export interface Experience {
  company: string;
  location: string;
  role: string;
  period: string;
  bullets: string[];
  backendBullets?: string[];
}

export interface Project {
  name: string;
  tech: string;
  period: string;
  bullets: string[];
}

export interface Education {
  institution: string;
  location: string;
  degree: string;
  period: string;
}

export interface Course {
  name: string;
  provider: string;
  year?: string;
}

export const RESUME = {
  name: ${q(R.profile.name)},
  title: ${q(R.profile.role)},
  email: ${q(R.profile.email)},
  phone: ${q(R.profile.phone)},
  linkedinUrl: ${q(R.profile.links.find(l => l.label === 'LinkedIn')?.href ?? '')},

  summary: ${q(R.summary)},

  skills: [
${skillsTs}
  ],

  experiences: [
${experienceTs}
  ] as Experience[],

  projects: [
${projectsTs}
  ] as Project[],

  education: [
${educationTs}
  ] as Education[],

  courses: [
${coursesTs}
  ] as Course[],
};
`;

writeFileSync(TS_OUT, ts, 'utf-8');
console.log(`✓  Written: src/app/data/resume-data.ts`);

// ─── Regenerate PDF ───────────────────────────────────────────────────────────

console.log('▸ Regenerating PDF…');
execSync(`node ${resolve(__dirname, 'generate-pdf.mjs')}`, {
  stdio: 'inherit',
  cwd: ROOT,
});

console.log('\n✓  Sync complete. Edit RESUME.md to update everything.');
