// AUTO-GENERATED by scripts/sync-resume.mjs — edit RESUME.md, not this file.

export interface Experience {
  company: string;
  location: string;
  role: string;
  period: string;
  bullets: string[];
  backendBullets?: string[];
  backendLabel?: string;
}

export interface Project {
  name: string;
  tech: string;
  period: string;
  bullets: string[];
}

export interface Education {
  institution: string;
  location: string;
  degree: string;
  period: string;
}

export interface Course {
  name: string;
  provider: string;
  year?: string;
}

export const RESUME = {
  name: "Iman Amini",
  title: "Software Engineer",
  subtitle: "Front-End Focused · Full-Stack with Java / Spring Boot",
  email: "iman.fa88@gmail.com",
  phone: "+98-9034646366",
  linkedinUrl: "https://www.linkedin.com/in/imanamini78",

  summary: "Software engineer focused on front-end with production backend experience — 5+ years of Angular and TypeScript at scale in fintech, plus Java 21 / Spring Boot services, relational and document databases, and the infrastructure that runs them. Led Credit & BNPL flows serving 10M+ users at Iran's largest digital payment platform and architected 14 shared npm packages across a 75-package monorepo. Founder and sole engineer of XPCard, an e-commerce platform for digital goods built from scratch in three months: a Spring Boot modular monolith on MySQL, MongoDB and Redis, contract-first OpenAPI APIs, Angular storefront and admin apps, and a Dockerized production stack. It reached 250 transactions with no marketing budget. Designed a contract-first, AI-assisted engineering workflow (Claude Code agents for planning, implementation, QA and review) with human-owned architecture and approval gates.",

  skills: [
    "Angular",
    "TypeScript",
    "RxJS",
    "Signals",
    "NX Monorepo",
    "React",
    "Next.js",
    "Vue",
    "Nuxt",
    "Java 21",
    "Spring Boot",
    "JPA / Hibernate",
    "MySQL",
    "MongoDB",
    "Redis",
    "REST / OpenAPI",
    "Testcontainers",
    "Docker",
    "CI/CD",
    "Playwright",
    "Jest",
    "Karma/Jasmine",
    "SCSS/CSS",
    "WordPress / PHP",
    "Technical SEO",
    "AI-assisted development (Claude Code)",
    "Git",
    "Figma",
    "Agile/Scrum",
  ],

  experiences: [
    {
      company: "Digipay",
      location: "Tehran",
      role: "Senior Front-End Engineer",
      period: "Dec 2021 – Present",
      bullets: [
    "Migrated three standalone Angular applications (web-wallet, credit, merchant-credit) into a unified NX monorepo with shared libs/ structure, consolidating dependencies and enabling cross-app code reuse.",
    "Established a multi-layer testing strategy across 75 shared npm packages: Karma/Jasmine unit tests for signal-based component logic and OnPush behavioral contracts, Playwright E2E tests for computed CSS, animation, and input-variant contracts, and a dual snapshot system (style .txt + visual .png) as backward-compatibility guards.",
    "Engineered a 7-step credit pre-registration state machine with conditional step-skipping logic, BehaviorSubject-driven reactive state, dynamic plan filtering by fund provider and collateral type, and bidirectional URL–step synchronization via query parameters.",
    "Built zero-dependency pinch-to-zoom, pan, and double-tap gesture directives for document image inspection, implementing multi-touch distance calculation, boundary-constrained CSS transforms, and requestAnimationFrame-throttled magnifier with rotation-aware coordinate mapping.",
    "Designed a Claude AI–assisted test generation pipeline for a 75-package Angular component library, engineering a 900-line reusable prompt specification that encodes testing principles, Angular signal patterns, OnPush behavioral contracts, and Playwright pitfalls.",
    "Built a zero-maintenance test catalog CLI (generate-package-status.mjs) that auto-discovers unit and E2E specs across all 75 packages, counts individual test cases via regex, and generates a typed TypeScript data file powering a live status dashboard.",
    "Adopted Angular 17+ standalone components, OnPush change detection, and signal-based computed properties across the entire Credit/BNPL library, eliminating NgModule overhead.",
    "Implemented a custom Angular preloading strategy using route metadata (preload: true, critical: true) to load critical routes immediately post-bootstrap, alongside retryImport wrappers for network-resilient lazy module loading.",
    "Integrated multi-platform analytics (Google Tag Manager, a marketing-automation SDK, Sentry) behind a single EventManagementService abstraction, with Sentry configured for performance profiling and console-error capture.",
    "Built biometric identity verification feature with selfie video capture and liveness photo for digital document signing.",
    "Developed Mydigipay website by Laravel & Angular.",
  ],
      backendBullets: [
      "Instrumented the Credit Onboarding Java (Spring Boot) service end-to-end with Micrometer metrics — campaign wallet creation, credit scoring, OTP (send / resend / verify), BNPL inquiry & allocation, sequential and volunteer activation flows.",
      "Fixed production Java bugs across microservices: NullPointerException in the blocking-detail service, journal double-linking on duplicate trackingCodes, and BNPL SMS double-activation — each covered with unit tests.",
      "Implemented a configurable time-window scoring-provider switch in the credit-scoring Java service, enabling dynamic selection between two external scoring engines on a scheduled basis.",
      "Built bank-partnership Credit Club and Installment Cheque landing pages in PHP on the Digipay marketing website, integrating credit-installment REST APIs.",
    ],
      backendLabel: "Backend Contributions",
    },
    {
      company: "XPCard",
      location: "Remote",
      role: "Founder & Software Engineer",
      period: "Jul 2026 – Present",
      bullets: [
    "Architected a four-repository system: a platform repo for product docs, API contracts and infrastructure, a Spring Boot backend, an Angular / Nx front-end monorepo with storefront and admin apps, and a CMS theme for the marketing site.",
    "Built the storefront and admin dashboard in Angular 20 on Nx: standalone components, signals, OnPush everywhere, domain libraries split into feature / ui / data-access layers with enforced boundaries, an RTL design system, Jest unit tests and Playwright E2E.",
    "Built a multi-agent development pipeline with Claude Code: a PM agent turns the PRD into feature briefs, an architect agent turns a brief into an API contract and per-repo tasks, and each repo runs dev → adversarial QA → code-review agents against written acceptance criteria. Every merge to production goes through my review.",
    "Encoded engineering standards as guardrails the agents cannot skip: per-repo coding rules, Definition-of-Done gates (lint, tests, build), design-to-code checks with Playwright screenshots, git hooks that block direct pushes to production, and build-time configuration guards.",
    "Delivered about 115 features and 880+ tasks in three months, a pace a solo engineer could not reach without the pipeline, with test coverage and contract parity enforced on every change.",
  ],
      backendBullets: [
      "Designed the backend as a Java 21 / Spring Boot 3 modular monolith with 10+ domain modules (catalog, order, payment, wallet, auth, discount, KYC, supplier, admin, chat-bot) that talk only through public service interfaces, with layered api → service → repository packages and DTOs at every boundary.",
      "Ran the API contract-first: 27 OpenAPI 3.1 specs are the single boundary between front-end and back-end, with versioned paths, RFC-7807 problem-detail errors and integer minor-unit money end to end.",
      "Modeled persistence per workload: MySQL with JPA and 140+ versioned Flyway migrations for transactional data (orders, payments, wallet ledger), MongoDB for the flexible product catalog, and Redis for OTP codes, rate limiting and caching.",
      "Built the order and payment core: an order state machine, integrations with multiple payment gateways, a customer wallet, bulk discount-code batches, and phone-OTP authentication with JWT sessions.",
      "Automated fulfillment through wholesale supplier APIs: scheduled catalog sync, automatic purchase and delivery of digital codes, signed webhook handling and a supplier ledger, with real purchases gated behind a feature flag for safe rehearsal.",
      "Covered the backend with nearly 1,000 test files — fast Mockito unit tests plus Testcontainers integration tests on real MySQL, MongoDB and Redis, sharing one Spring context to keep the full suite fast.",
      "Run production myself: Docker Compose on a single VPS, self-hosted GitHub Actions runners with deploy locking, a TLS edge proxy, CDN and page caching, and a rehearsal environment seeded from anonymized production data for risky migrations.",
    ],
      backendLabel: "Backend Engineering",
    },
    {
      company: "Adowing",
      location: "Tehran",
      role: "Front-End Developer",
      period: "Oct 2019 – Dec 2021",
      bullets: [
    "Developed internal panels for the marketing team, accounting team & other departments.",
    "Built pixel-perfect UIs in different sizes according to the design.",
    "Researched the agile approach with the product team and implemented it.",
    "Researched test methods like unit test, integration test, regression test & acceptance test.",
    "Researched clean code methods and developed products with them.",
    "Mentored a front-end developer intern.",
  ],
    },
    {
      company: "Carnotic",
      location: "Tehran",
      role: "Front-End Developer",
      period: "Oct 2019 – Dec 2021",
      bullets: [
    "Implemented a highly responsive user interface for a freight forwarding platform.",
    "Built pixel-perfect UIs in different sizes according to the design.",
    "Packed customized video player from \"Talent Academy\" project and used in Carnotic.",
    "Implemented this Nuxt app for SEO purposes.",
    "Documented components and wrote test cases for all methods.",
  ],
    },
    {
      company: "Freelance",
      location: "Tehran",
      role: "Android Developer",
      period: "Oct 2014 – Oct 2015",
      bullets: [
    "Developed 10 apps and published them on the main Iranian Android app stores.",
    "Implemented with B4A (Basic for Android) that is based on VisualBasic language.",
    "All applications were content-driven.",
  ],
    }
  ] as Experience[],

  projects: [
    {
      name: "Pita",
      tech: "React · NX Monorepo · WebSockets · Docker · TypeScript",
      period: "2024 – 2025",
      bullets: [
    "A two-app React/NX monorepo for self-service restaurant ordering — a customer-facing kiosk and a kitchen display — sharing @pita/api and @pita/ui, deployed as separate Docker images behind nginx routing.",
    "Integrated the Epson ePOS SDK for thermal receipt printing with automatic network → USB fallback, plus mobile-device and browser-print safety nets.",
    "Real-time order sync between kiosk and kitchen over Laravel Echo + Pusher WebSockets, with a 10-second polling backup and a live in-process vs ready KDS board.",
    "Zero-downtime version checker for always-on hardware — polls a cache-busted /version.json and forces a hard reload on new builds.",
  ],
    },
    {
      name: "Pharma",
      tech: "Angular 17 · PWA · Signals · Service Worker",
      period: "2024",
      bullets: [
    "A full Angular 17 PWA for prescription pharmaceutical e-commerce, built around a server-driven adaptive questionnaire engine with offline support.",
    "Server-driven adaptive medical questionnaire (SingleChoice / MultipleChoice / FormFill / Terminate) — each question fetched from the API based on the previous answer for personalised eligibility screening.",
    "Signal-based session management, CAPTCHA-protected auth, multi-step drug selection & checkout, in-app support chat, and a Service Worker for offline use.",
  ],
    },
    {
      name: "Talent Academy",
      tech: "Vue · Custom video player",
      period: "2021",
      bullets: [
    "Interactive video player with playlists, instructor feedback messages, and global SSO for internal platforms.",
  ],
    },
    {
      name: "Majid",
      tech: "Angular · Complex JSON",
      period: "2020 – 2021",
      bullets: [
    "Drag-and-drop, JotForm-style form builder — schema-driven UI with deep nested-JSON handling and live preview.",
  ],
    }
  ] as Project[],

  education: [
    {
      institution: "Islamic Azad University Central Tehran Branch",
      location: "Tehran",
      degree: "Computer Engineering — Bachelor",
      period: "2017 – 2022",
    },
    {
      institution: "Imam Sadiq Highschool",
      location: "Tehran",
      degree: "Mathematics and Physics — Diploma",
      period: "2013 – 2017",
    }
  ] as Education[],

  courses: [
    { name: "Claude Code in Action", provider: "Anthropic", year: "Feb 2026" },
    { name: "The Complete Guide to Becoming a Software Architect", provider: "Udemy", year: "Apr 2025" },
    { name: "Angular — The Complete Guide (2024 Edition)", provider: "Udemy" },
    { name: "UTACM-Cafebazaar Android Course", provider: "Cafebazaar & University of Tehran", year: "Winter 2019" },
    { name: "Agile Software Development: Clean Coding Practices", provider: "LinkedIn" },
    { name: "Agile Software Development: Refactoring", provider: "LinkedIn" },
    { name: "JavaScript: Classes", provider: "LinkedIn" },
    { name: "Test Automation Foundations", provider: "LinkedIn" },
    { name: "Agile Testing", provider: "LinkedIn" },
    { name: "Bootstrap 4 with Sass", provider: "LinkedIn" },
    { name: "Interactive Animations with CSS and JavaScript", provider: "LinkedIn" },
    { name: "JavaScript for Web Designers", provider: "LinkedIn" }
  ] as Course[],
};
