// AUTO-GENERATED by scripts/sync-resume.mjs — edit RESUME.md, not this file.

export interface Experience {
  company: string;
  location: string;
  role: string;
  period: string;
  bullets: string[];
  backendBullets?: string[];
}

export interface Project {
  name: string;
  tech: string;
  period: string;
  bullets: string[];
}

export interface Education {
  institution: string;
  location: string;
  degree: string;
  period: string;
}

export interface Course {
  name: string;
  provider: string;
  year?: string;
}

export const RESUME = {
  name: "Iman Amini",
  title: "Senior Front-End Engineer",
  email: "iman.fa88@gmail.com",
  phone: "+98-9034646366",
  linkedinUrl: "https://www.linkedin.com/in/imanamini78",

  summary: "Frontend-heavy engineer with cross-stack experience — 5+ years specializing in Angular and TypeScript at scale in fintech, with backend contributions in Java (Spring Boot) microservices and PHP. Led development of Credit & BNPL flows serving 10M+ users at Iran's largest digital payment platform. Architected 14 shared npm packages and established multi-layer testing strategies across 75-package monorepos. Fluent across Angular, React/Next.js, and Vue/Nuxt — known for picking up new stacks quickly and thriving in cross-functional teams.",

  skills: [
    "Angular",
    "TypeScript",
    "RxJS",
    "NX Monorepo",
    "React",
    "Next.js",
    "Vue",
    "Nuxt",
    "Playwright",
    "Karma/Jasmine",
    "SCSS/CSS",
    "Java / Spring Boot",
    "PHP",
    "Git",
    "REST APIs",
    "Figma",
    "Agile/Scrum",
  ],

  experiences: [
    {
      company: "Digipay",
      location: "Tehran",
      role: "Senior Front-End Engineer",
      period: "Dec 2021 – Present",
      bullets: [
    "Migrated three standalone Angular applications (web-wallet, credit, merchant-credit) into a unified NX monorepo with shared libs/ structure, consolidating dependencies and enabling cross-app code reuse.",
    "Established a multi-layer testing strategy across 75 shared npm packages: Karma/Jasmine unit tests for signal-based component logic and OnPush behavioral contracts, Playwright E2E tests for computed CSS, animation, and input-variant contracts, and a dual snapshot system (style .txt + visual .png) as backward-compatibility guards.",
    "Engineered a 7-step credit pre-registration state machine with conditional step-skipping logic, BehaviorSubject-driven reactive state, dynamic plan filtering by fund provider and collateral type, and bidirectional URL–step synchronization via query parameters.",
    "Built zero-dependency pinch-to-zoom, pan, and double-tap gesture directives for document image inspection, implementing multi-touch distance calculation, boundary-constrained CSS transforms, and requestAnimationFrame-throttled magnifier with rotation-aware coordinate mapping.",
    "Designed a Claude AI–assisted test generation pipeline for a 75-package Angular component library, engineering a 900-line reusable prompt specification that encodes testing principles, Angular signal patterns, OnPush behavioral contracts, and Playwright pitfalls.",
    "Built a zero-maintenance test catalog CLI (generate-package-status.mjs) that auto-discovers unit and E2E specs across all 75 packages, counts individual test cases via regex, and generates a typed TypeScript data file powering a live status dashboard.",
    "Adopted Angular 17+ standalone components, OnPush change detection, and signal-based computed properties across the entire Credit/BNPL library, eliminating NgModule overhead.",
    "Implemented a custom Angular preloading strategy using route metadata (preload: true, critical: true) to load critical routes immediately post-bootstrap, alongside retryImport wrappers for network-resilient lazy module loading.",
    "Integrated multi-platform analytics (Google Tag Manager, InTrack, Sentry) behind a single EventManagementService abstraction, with Sentry configured for performance profiling and console-error capture.",
    "Built biometric identity verification feature with selfie video capture and liveness photo for digital document signing.",
    "Developed Mydigipay website by Laravel & Angular.",
  ],
      backendBullets: [
      "Instrumented the Credit Onboarding Java (Spring Boot) service end-to-end with Micrometer metrics — campaign wallet creation, SMC scoring, ICS OTP (send / resend / verify), BNPL inquiry & allocation, sequential and volunteer activation flows.",
      "Fixed production Java bugs across microservices: NullPointerException in the blocking-detail service, journal double-linking on duplicate trackingCodes, and BNPL SMS double-activation — each covered with unit tests.",
      "Implemented a configurable time-window scoring-provider switch in the SMC Java service, enabling dynamic selection between ICS and BANK_SCORE engines on a scheduled basis.",
      "Built Credit Club (Mellat & Tejarat) and Installment Cheque landing pages in PHP on the Digipay marketing website, integrating credit-installment REST APIs.",
    ],
    },
    {
      company: "Adowing",
      location: "Tehran",
      role: "Front-End Developer",
      period: "Oct 2019 – Dec 2021",
      bullets: [
    "Developed internal panels for the marketing team, accounting team & other departments.",
    "Built pixel-perfect UIs in different sizes according to the design.",
    "Researched the agile approach with the product team and implemented it.",
    "Researched test methods like unit test, integration test, regression test & acceptance test.",
    "Researched clean code methods and developed products with them.",
    "Mentored a front-end developer intern.",
  ],
    },
    {
      company: "Carnotic",
      location: "Tehran",
      role: "Front-End Developer",
      period: "Oct 2019 – Dec 2021",
      bullets: [
    "Implemented a highly responsive user interface for a freight forwarding platform.",
    "Built pixel-perfect UIs in different sizes according to the design.",
    "Packed customized video player from \"Talent Academy\" project and used in Carnotic.",
    "Implemented this Nuxt app for SEO purposes.",
    "Documented components and wrote test cases for all methods.",
  ],
    },
    {
      company: "Freelance",
      location: "Tehran",
      role: "Android Developer",
      period: "Oct 2014 – Oct 2015",
      bullets: [
    "Developed 10 apps and published them in Cafebazaar, Myket and Candoo.",
    "Implemented with B4A (Basic for Android) that is based on VisualBasic language.",
    "All applications were content-driven.",
  ],
    }
  ] as Experience[],

  projects: [
    {
      name: "Pita",
      tech: "React · NX Monorepo · WebSockets · Docker · TypeScript",
      period: "2024 – 2025",
      bullets: [
    "A two-app React/NX monorepo for self-service restaurant ordering — a customer-facing kiosk and a kitchen display — sharing @pita/api and @pita/ui, deployed as separate Docker images behind nginx routing.",
    "Integrated the Epson ePOS SDK for thermal receipt printing with automatic network → USB fallback, plus mobile-device and browser-print safety nets.",
    "Real-time order sync between kiosk and kitchen over Laravel Echo + Pusher WebSockets, with a 10-second polling backup and a live in-process vs ready KDS board.",
    "Zero-downtime version checker for always-on hardware — polls a cache-busted /version.json and forces a hard reload on new builds.",
  ],
    },
    {
      name: "Pharma",
      tech: "Angular 17 · PWA · Signals · Service Worker",
      period: "2024",
      bullets: [
    "A full Angular 17 PWA for prescription pharmaceutical e-commerce, built around a server-driven adaptive questionnaire engine with offline support.",
    "Server-driven adaptive medical questionnaire (SingleChoice / MultipleChoice / FormFill / Terminate) — each question fetched from the API based on the previous answer for personalised eligibility screening.",
    "Signal-based session management, CAPTCHA-protected auth, multi-step drug selection & checkout, in-app support chat, and a Service Worker for offline use.",
  ],
    },
    {
      name: "Talent Academy",
      tech: "Vue · Custom video player",
      period: "2021",
      bullets: [
    "Interactive video player with playlists, instructor feedback messages, and global SSO for internal platforms.",
  ],
    },
    {
      name: "Majid",
      tech: "Angular · Complex JSON",
      period: "2020 – 2021",
      bullets: [
    "Drag-and-drop, JotForm-style form builder — schema-driven UI with deep nested-JSON handling and live preview.",
  ],
    }
  ] as Project[],

  education: [
    {
      institution: "Islamic Azad University Central Tehran Branch",
      location: "Tehran",
      degree: "Computer Engineering — Bachelor",
      period: "2017 – 2022",
    },
    {
      institution: "Imam Sadiq Highschool",
      location: "Tehran",
      degree: "Mathematics and Physics — Diploma",
      period: "2013 – 2017",
    }
  ] as Education[],

  courses: [
    { name: "Claude Code in Action", provider: "Anthropic", year: "Feb 2026" },
    { name: "The Complete Guide to Becoming a Software Architect", provider: "Udemy", year: "Apr 2025" },
    { name: "Angular — The Complete Guide (2024 Edition)", provider: "Udemy" },
    { name: "UTACM-Cafebazaar Android Course", provider: "Cafebazaar & University of Tehran", year: "Winter 2019" },
    { name: "Agile Software Development: Clean Coding Practices", provider: "LinkedIn" },
    { name: "Agile Software Development: Refactoring", provider: "LinkedIn" },
    { name: "JavaScript: Classes", provider: "LinkedIn" },
    { name: "Test Automation Foundations", provider: "LinkedIn" },
    { name: "Agile Testing", provider: "LinkedIn" },
    { name: "Bootstrap 4 with Sass", provider: "LinkedIn" },
    { name: "Interactive Animations with CSS and JavaScript", provider: "LinkedIn" },
    { name: "JavaScript for Web Designers", provider: "LinkedIn" }
  ] as Course[],
};
