// AUTO-GENERATED by scripts/sync-resume.mjs — edit RESUME.md, not this file.

export interface Experience {
  company: string;
  location: string;
  role: string;
  period: string;
  bullets: string[];
  backendBullets?: string[];
}

export interface Project {
  name: string;
  tech: string;
  period: string;
  bullets: string[];
}

export interface Education {
  institution: string;
  location: string;
  degree: string;
  period: string;
}

export interface Course {
  name: string;
  provider: string;
  year?: string;
}

export const RESUME = {
  name: "Iman Amini",
  title: "Software Engineer",
  subtitle: "Focused on Front-End · Angular · TypeScript · React",
  email: "iman.fa88@gmail.com",
  phone: "+98-9034646366",
  linkedinUrl: "https://www.linkedin.com/in/imanamini78",

  summary: "Software engineer focused on front-end — 5+ years specializing in Angular and TypeScript at scale in fintech, with hands-on backend work in Java (Spring Boot) and PHP. Led development of Credit & BNPL flows serving 10M+ users at Iran's largest digital payment platform, and architected 14 shared npm packages across a 75-package monorepo. Founder and sole engineer of XPCard (xpcard.ir), a production e-commerce platform built from scratch in three months (Angular 20 / Nx, Spring Boot 3 / Java 21, MySQL, MongoDB, Redis, Docker, WordPress) that reached 250 transactions with no marketing budget. Designed a contract-first, AI-assisted engineering workflow (Claude Code agents for planning, implementation, QA and review) with human-owned architecture and approval gates. Fluent across Angular, React/Next.js and Vue/Nuxt.",

  skills: [
    "Angular",
    "TypeScript",
    "RxJS",
    "Signals",
    "NX Monorepo",
    "React",
    "Next.js",
    "Vue",
    "Nuxt",
    "Playwright",
    "Jest",
    "Karma/Jasmine",
    "SCSS/CSS",
    "Java / Spring Boot",
    "MySQL",
    "MongoDB",
    "Redis",
    "OpenAPI",
    "Docker",
    "CI/CD",
    "WordPress / PHP",
    "Technical SEO",
    "AI-assisted development (Claude Code)",
    "Git",
    "Figma",
    "Agile/Scrum",
  ],

  experiences: [
    {
      company: "XPCard (xpcard.ir)",
      location: "Tehran · Remote",
      role: "Founder & Software Engineer",
      period: "Jul 2026 – Present",
      bullets: [
    "Architected a four-repo system: a platform repo for product docs, OpenAPI contracts and infra, an Angular 20 / Nx front-end monorepo (storefront + admin apps), a Spring Boot 3 / Java 21 modular monolith, and a WordPress child theme for the marketing site and magazine.",
    "Made the API contract-first: 27 OpenAPI 3.1 specs are the single boundary between front-end and back-end, with typed mocks so the UI and the API could be built and tested independently, plus RFC-7807 errors and integer-rial money end to end.",
    "Built the storefront and admin dashboard in Angular 20 on Nx: standalone components, signals, OnPush everywhere, domain libs split into feature / ui / data-access layers with enforced boundaries, Persian RTL design system, Jest unit tests and Playwright E2E.",
    "Designed the backend as a modular monolith (catalog, order, payment, wallet, auth, discount, KYC, provider, admin, telegram) with MySQL + Flyway (146 migrations), MongoDB for the flexible product catalog and Redis for OTP, rate limits and caching, covered by Testcontainers integration tests.",
    "Integrated three payment gateways and two wholesale supplier APIs (catalog sync, automated order fulfillment, webhooks, provider ledger), SMS OTP login, and a Telegram bot that reuses the same domain services as the web checkout.",
    "Built a multi-agent development pipeline with Claude Code: a PM agent turns the PRD into feature briefs, an architect agent turns a brief into a contract and per-repo tasks, and each repo runs dev → adversarial QA → code-review agents against written acceptance criteria. Every merge to production goes through my review.",
    "Encoded engineering standards as guardrails the agents cannot skip: per-repo coding rules, Definition of Done gates (lint, tests, build), design-to-code checks against delivered HTML designs with Playwright screenshots, git hooks that block direct pushes to production, and build-time guards for caching and JSON-LD safety.",
    "Delivered about 115 features and 880+ tasks across the four repos in three months, at a pace a solo engineer could not reach without the pipeline, while keeping test coverage and contract parity enforced on every change.",
    "Run production myself: Docker Compose on a single VPS, self-hosted GitHub Actions runners with deploy locking, TLS edge, ArvanCloud CDN, WP Super Cache, and a demo environment seeded from anonymized production data for rehearsing risky migrations.",
  ],
    },
    {
      company: "Digipay",
      location: "Tehran",
      role: "Senior Front-End Engineer",
      period: "Dec 2021 – Present",
      bullets: [
    "Migrated three standalone Angular applications (web-wallet, credit, merchant-credit) into a unified NX monorepo with shared libs/ structure, consolidating dependencies and enabling cross-app code reuse.",
    "Established a multi-layer testing strategy across 75 shared npm packages: Karma/Jasmine unit tests for signal-based component logic and OnPush behavioral contracts, Playwright E2E tests for computed CSS, animation, and input-variant contracts, and a dual snapshot system (style .txt + visual .png) as backward-compatibility guards.",
    "Engineered a 7-step credit pre-registration state machine with conditional step-skipping logic, BehaviorSubject-driven reactive state, dynamic plan filtering by fund provider and collateral type, and bidirectional URL–step synchronization via query parameters.",
    "Built zero-dependency pinch-to-zoom, pan, and double-tap gesture directives for document image inspection, implementing multi-touch distance calculation, boundary-constrained CSS transforms, and requestAnimationFrame-throttled magnifier with rotation-aware coordinate mapping.",
    "Designed a Claude AI–assisted test generation pipeline for a 75-package Angular component library, engineering a 900-line reusable prompt specification that encodes testing principles, Angular signal patterns, OnPush behavioral contracts, and Playwright pitfalls.",
    "Built a zero-maintenance test catalog CLI (generate-package-status.mjs) that auto-discovers unit and E2E specs across all 75 packages, counts individual test cases via regex, and generates a typed TypeScript data file powering a live status dashboard.",
    "Adopted Angular 17+ standalone components, OnPush change detection, and signal-based computed properties across the entire Credit/BNPL library, eliminating NgModule overhead.",
    "Implemented a custom Angular preloading strategy using route metadata (preload: true, critical: true) to load critical routes immediately post-bootstrap, alongside retryImport wrappers for network-resilient lazy module loading.",
    "Integrated multi-platform analytics (Google Tag Manager, InTrack, Sentry) behind a single EventManagementService abstraction, with Sentry configured for performance profiling and console-error capture.",
    "Built biometric identity verification feature with selfie video capture and liveness photo for digital document signing.",
    "Developed Mydigipay website by Laravel & Angular.",
  ],
      backendBullets: [
      "Instrumented the Credit Onboarding Java (Spring Boot) service end-to-end with Micrometer metrics — campaign wallet creation, SMC scoring, ICS OTP (send / resend / verify), BNPL inquiry & allocation, sequential and volunteer activation flows.",
      "Fixed production Java bugs across microservices: NullPointerException in the blocking-detail service, journal double-linking on duplicate trackingCodes, and BNPL SMS double-activation — each covered with unit tests.",
      "Implemented a configurable time-window scoring-provider switch in the SMC Java service, enabling dynamic selection between ICS and BANK_SCORE engines on a scheduled basis.",
      "Built Credit Club (Mellat & Tejarat) and Installment Cheque landing pages in PHP on the Digipay marketing website, integrating credit-installment REST APIs.",
    ],
    },
    {
      company: "Adowing",
      location: "Tehran",
      role: "Front-End Developer",
      period: "Oct 2019 – Dec 2021",
      bullets: [
    "Developed internal panels for the marketing team, accounting team & other departments.",
    "Built pixel-perfect UIs in different sizes according to the design.",
    "Researched the agile approach with the product team and implemented it.",
    "Researched test methods like unit test, integration test, regression test & acceptance test.",
    "Researched clean code methods and developed products with them.",
    "Mentored a front-end developer intern.",
  ],
    },
    {
      company: "Carnotic",
      location: "Tehran",
      role: "Front-End Developer",
      period: "Oct 2019 – Dec 2021",
      bullets: [
    "Implemented a highly responsive user interface for a freight forwarding platform.",
    "Built pixel-perfect UIs in different sizes according to the design.",
    "Packed customized video player from \"Talent Academy\" project and used in Carnotic.",
    "Implemented this Nuxt app for SEO purposes.",
    "Documented components and wrote test cases for all methods.",
  ],
    },
    {
      company: "Freelance",
      location: "Tehran",
      role: "Android Developer",
      period: "Oct 2014 – Oct 2015",
      bullets: [
    "Developed 10 apps and published them in Cafebazaar, Myket and Candoo.",
    "Implemented with B4A (Basic for Android) that is based on VisualBasic language.",
    "All applications were content-driven.",
  ],
    }
  ] as Experience[],

  projects: [
    {
      name: "Pita",
      tech: "React · NX Monorepo · WebSockets · Docker · TypeScript",
      period: "2024 – 2025",
      bullets: [
    "A two-app React/NX monorepo for self-service restaurant ordering — a customer-facing kiosk and a kitchen display — sharing @pita/api and @pita/ui, deployed as separate Docker images behind nginx routing.",
    "Integrated the Epson ePOS SDK for thermal receipt printing with automatic network → USB fallback, plus mobile-device and browser-print safety nets.",
    "Real-time order sync between kiosk and kitchen over Laravel Echo + Pusher WebSockets, with a 10-second polling backup and a live in-process vs ready KDS board.",
    "Zero-downtime version checker for always-on hardware — polls a cache-busted /version.json and forces a hard reload on new builds.",
  ],
    },
    {
      name: "Pharma",
      tech: "Angular 17 · PWA · Signals · Service Worker",
      period: "2024",
      bullets: [
    "A full Angular 17 PWA for prescription pharmaceutical e-commerce, built around a server-driven adaptive questionnaire engine with offline support.",
    "Server-driven adaptive medical questionnaire (SingleChoice / MultipleChoice / FormFill / Terminate) — each question fetched from the API based on the previous answer for personalised eligibility screening.",
    "Signal-based session management, CAPTCHA-protected auth, multi-step drug selection & checkout, in-app support chat, and a Service Worker for offline use.",
  ],
    },
    {
      name: "Talent Academy",
      tech: "Vue · Custom video player",
      period: "2021",
      bullets: [
    "Interactive video player with playlists, instructor feedback messages, and global SSO for internal platforms.",
  ],
    },
    {
      name: "Majid",
      tech: "Angular · Complex JSON",
      period: "2020 – 2021",
      bullets: [
    "Drag-and-drop, JotForm-style form builder — schema-driven UI with deep nested-JSON handling and live preview.",
  ],
    }
  ] as Project[],

  education: [
    {
      institution: "Islamic Azad University Central Tehran Branch",
      location: "Tehran",
      degree: "Computer Engineering — Bachelor",
      period: "2017 – 2022",
    },
    {
      institution: "Imam Sadiq Highschool",
      location: "Tehran",
      degree: "Mathematics and Physics — Diploma",
      period: "2013 – 2017",
    }
  ] as Education[],

  courses: [
    { name: "Claude Code in Action", provider: "Anthropic", year: "Feb 2026" },
    { name: "The Complete Guide to Becoming a Software Architect", provider: "Udemy", year: "Apr 2025" },
    { name: "Angular — The Complete Guide (2024 Edition)", provider: "Udemy" },
    { name: "UTACM-Cafebazaar Android Course", provider: "Cafebazaar & University of Tehran", year: "Winter 2019" },
    { name: "Agile Software Development: Clean Coding Practices", provider: "LinkedIn" },
    { name: "Agile Software Development: Refactoring", provider: "LinkedIn" },
    { name: "JavaScript: Classes", provider: "LinkedIn" },
    { name: "Test Automation Foundations", provider: "LinkedIn" },
    { name: "Agile Testing", provider: "LinkedIn" },
    { name: "Bootstrap 4 with Sass", provider: "LinkedIn" },
    { name: "Interactive Animations with CSS and JavaScript", provider: "LinkedIn" },
    { name: "JavaScript for Web Designers", provider: "LinkedIn" }
  ] as Course[],
};
